[package]
name = "strawdog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
typed-builder = "0.9.1"
async-trait = "0.1.52"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0.52"
lazy_static = "1.4.0"
inventory = "0.2.1"
opentelemetry = "0.16.0"
futures = "0.3.18"
tower = {version="0.4.11", features=["limit", "util"]}
http = "0.2.5"
maplit = "1.0.2"
