server:
  cors:
    origins:
      - "https://studio.apollographql.com/"
plugins:
  apollographql.mock-subgraph:
    path: "supergraph.graphql"
    # removing this key would apply the plugin
    # to every services
    services:
      - accounts
